### ISSUE TITLE
java版本是java version "1.8.0_181" 但导入burp失败

### ISSUE THREAD

**Issue by Dawson0x00** [undefinedsec/HaE-Java#2]
java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.acu.a(Unknown Source)
	at burp.acu.<init>(Unknown Source)
	at burp.m.a(Unknown Source)
	at burp.ey9.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

➜  ~ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by Dawson0x00** [comment]
尝试 burp1.7.31 与burp2.0.0.6版本都不可以

**Comment by undefinedsec** [comment]
> java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> at java.lang.ClassLoader.defineClass1(Native Method)
> at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> at java.lang.Class.forName0(Native Method)
> at java.lang.Class.forName(Class.java:348)
> at burp.acu.a(Unknown Source)
> at burp.acu.(Unknown Source)
> at burp.m.a(Unknown Source)
> at burp.ey9.lambda$panelLoaded$0(Unknown Source)
> at java.lang.Thread.run(Thread.java:748)
> The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.
> 
> ➜ ~ java -version
> java version "1.8.0_181"
> Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

你java版本太低了，换成11.0.1以上才可以。

**Comment by undefinedsec** [comment]
> 尝试 burp1.7.31 与burp2.0.0.6版本都不可以

跟burp没关系，跟你本机的Java版本或者你起Burp的Java版本有关系。

**Comment by undefinedsec** [comment]
Java版本已降低为"1.7.0_80"，请用https://github.com/undefinedsec/HaE-Java/releases/tag/v0.4重试。

**Comment by Dawson0x00** [comment]
我用java version "14.0.1 burp2020最新版无法启动 呜呜

**Comment by Dawson0x00** [comment]
好的 谢谢 我试试这个链接下

**Comment by Dawson0x00** [comment]
我用java version "14.0.1 burp2020最新版无法启动burp2020 呜呜

**Comment by Dawson0x00** [comment]
低版本的ok了～

**Comment by Dawson0x00** [comment]
tool很赞～ 提几个优化建议：
1. 如果能加上检测响应包参数就好了，比如请求参数如果有ecology_jsessionid rememberMe 参数，可能就存在某个rce漏洞测试点，测试思路
2. 匹配的结果能汇总输出就完美～

**Comment by undefinedsec** [comment]
> tool很赞～ 提几个优化建议：
> 
> 1. 如果能加上检测响应包参数就好了，比如请求参数如果有ecology_jsessionid rememberMe 参数，可能就存在某个rce漏洞测试点，测试思路
> 2. 匹配的结果能汇总输出就完美～

感谢反馈，后续找时间优化下。
